### PR TITLE
Substitute MSBuild variables such as $(ProjectDir)

### LINKED ISSUE #15: Doesn't allow for reference paths, creating challenges for build environments
Good package but would be great if it supported reference paths.

TextTransform.exe supports a -referencePaths switch that allows for customizing the reference paths that the T4 host (CommandLineHost) will use for internal assembly resolution and for ITextTemplatingEngineHost.ResolveAssemblyReference. It's not uncommon for a T4 to use ResolveAssemblyReference to resolve external dependencies.

TransformOnBuild does not support custom reference paths, nor does it automatically pass in the ($ProjectDir) or ($TargetDir) MSBuild variables as default reference paths.

Please consider adding this in future releases.

Thanks,
RyanF

### PR DESCRIPTION
**Pull request by mnaoumov**
Fixes #15

### CODE REVIEW

**Comment by mnaoumov** [comment]
Initially I was going to implement the fix in pure MSBuild but then I found it will be too verbose and unmaintainable. So then I decided to create a custom MSBuild task assembly to hold all the logic

**Comment by mnaoumov** [comment]
Implemented logic allows to substitute all *$(CsprojPropertyName)* and *%EnvironmentVariable%* names.
Note that you will not *$(SolutionDir)* resolved because its value exists only inside Visual Studio. You should use something like *$(ProjectDir)..\* instead

**Comment by mnaoumov** [comment]
I've created a temporary NuGet package which includes the fix until the author includes the fix in the official NuGet package

https://www.nuget.org/packages/Clarius.TransformOnBuild-unofficial/

**Comment by parnasoft** [comment]
I tried the latest with $(ProjectDir)..\ and does not seem to work.  It is still not able to resolve the path to the assembly.

**Comment by mnaoumov** [comment]
Thanks @parnasoft 

I found some issues
Updated my unofficial NuGet package: https://www.nuget.org/packages/Clarius.TransformOnBuild-unofficial
And created a demo to show that **$(ProjectDir)** is being resolved properly: https://github.com/mnaoumov/TransformOnBuild/archive/fix-15-demo.zip

**Comment by parnasoft** [comment]
@mnaoumov The latest one works.  Thanks,

**Comment by Sam13** [comment]
Does not work for me with
<#@ assembly name="$(TargetDir)\SomeAssembly.dll"  #>

**Comment by mnaoumov** [comment]
@Sam13 and it is logical. SomeAssembly.dll is being copied to TargetDir **after ** the compilation but T4 is being transformed **before** the compilation. Use something else rather than TargetDir

**Comment by Sam13** [comment]
This works when running the T4 directly in VS (from context menu).
The assembly is not the output of the current project, it already exists because built by another project before...

**Comment by mnaoumov** [comment]
@Sam13 I think the real reason why **$(TargetDir)** worked for you from Visual Studio for because the project was already compiled previously and therefore your target dir already contains the dll from previous build.

To prove my point, please right click on the solution node in the Solution Explorer and select **Clean Solution** and then try to run T4 via context menu. You'll see the error that it cannot find the assembly required. Even if you compile any other projects except the one that contains the T4 template (project A) and any projects that reference project A, the error will persist.

The key thing here that compilation and transformation are separate actions in Visual Studio.

However the nature of Clarius project is to transform template before the compilation and that's why we should not use anything like **$(TargetDir)**, **$(TargetPath)**, **$(OutDir)** etc,

Although, I understand the importance of your requirement and I'll create another pull request shortly

**Comment by mnaoumov** [comment]
@Sam13 , I've made a fix to make **$(TargetDir)** working. You can try it from the latest NuGet package https://www.nuget.org/packages/Clarius.TransformOnBuild-unofficial/ or check the demo I've created https://github.com/mnaoumov/TransformOnBuild/archive/fix-17-demo.zip

**Comment by Sam13** [comment]
@mnaoumov 
Thanks for your fix, I'll try it asap.
The T4 template executes also on a clean build.
As already said I'm trying to load an assembly which the project in which the T4 resides depends on. This means it is built before the T4 project is built. In my project I'll have the same output directory for all assemblies so $(TargetDir) points to a directory which contains already built assemblies for the current build.

**Comment by mnaoumov** [comment]
@Sam13, Visual Studio somehow caches the result dll. So if you do a solution cleanup and then reopen Visual Studio, you won't be able to transform the template from Visual Studio by context menu anymore.

If you have the same output directories for all projects I don't understand how the previous version did not work for you. I've created a test project with the previous version of NuGet package https://www.nuget.org/packages/Clarius.TransformOnBuild-unofficial/1.14.0 and it worked fine in such scenario

**Comment by Sam13** [comment]
@mnaoumov That's strange, will retest asap...

**Comment by mnaoumov** [comment]
@Sam13 , any luck with the example project? I'd like to investigate the problem

**Comment by Sam13** [comment]
Do you know where I can get some diagnostics output when the tool is running? Currently I just have the output file which contains "ErrorGeneratingOutput".

**Comment by mnaoumov** [comment]
@Sam13

In case if the template syntax is wrong itself, you should see some errors in Output Window in Visual Studio, or in command prompt if you build by MSBuild.

For more serious debugging you may try to add the following snippet into your template file

```
<#@ Template Debug="True" ... #@>
...
<# System.Diagnostics.Debugger.Launch(); System.Diagnostics.Debugger.Break(); #>
...

```

**Comment by Sam13** [comment]
Instrumented the failing T4 with the debugger option.
When I delete the output file of the T4 and run a clean build, the debugger is not going to be launched. I also set the MS build verbosity to "Detailed" but there is nothing shown in the output...

I assume that I have instrumented my T4 correctly since the debugger is launched when I trigger the execution manually.
Any ideas?

**Comment by mnaoumov** [comment]
@Sam13 Make sure that your tt files have **Build Action** = **None** rather than **Content**
Build Actiion = None

**Comment by Sam13** [comment]
Build Action of T4 file is already set to *None*

**Comment by mnaoumov** [comment]
@Sam13 Can you somehow share your project for me to be able to identify the issue?

**Comment by Sam13** [comment]
@mnaoumov No unfortunately that's not possible... I need some more time to investigate...

**Comment by mnaoumov** [comment]
@Sam13 , please try to replace all $(TargetDir) properties with absolute paths and install original NuGet package https://www.nuget.org/packages/Clarius.TransformOnBuild/ to check if it is a problem with my fork

**Comment by mnaoumov** [comment]
@Sam13 , I've created a demo which produces xaml, and it works for me. Please take a look https://github.com/mnaoumov/TransformOnBuild/archive/wpf-demo.zip

**Comment by Sam13** [comment]
@mnaoumov  Thanks for your time creating the XAML example. So this is not the problem.

When running with absolute paths, the official version works and unfortunately your's doesn't :-(.

**Comment by mnaoumov** [comment]
@Sam13 can you try to change your template to the simplest possible form like the one from the wpf demo? Just to check maybe it is some uncovered case with the template itself.

**Comment by mnaoumov** [comment]
@Sam13 In case if you would like to debug the custom task assembly, you may wish to enable pdbs back. You'll have to revert the commit https://github.com/mnaoumov/TransformOnBuild/commit/1ac6abee88664de1ecdf7b8c41ec5625590b2478

**Comment by Sam13** [comment]
@mnaoumov Thanks, already recovered the PDB ;-).
Now I was able to debug your custom task assembly and view the error messages in the debugger of the transform process which is started in the *RunTransformTool* method:
When the template is executed the assembly which is referenced does not exist. I think there is a misunderstanding on my side. I always thought the template is run when the project is being built, which means all references of this project have already built?

Another thing: Where does the *Microsoft.Build.Utilities.Task.Log* output go? Shouldn't that be written to the build output?

**Comment by mnaoumov** [comment]
@Sam13 , sorry I was not accurate enough with my WPF test. Actually you were right. It seems that xaml was compiled before the transformation

**Comment by mnaoumov** [comment]
@Sam13 I've updated my package to make WPF compilation working https://www.nuget.org/packages/Clarius.TransformOnBuild-unofficial/

I don't know how to reproduce the errors you are having. All error messages for my task are being propagated to the console.

Did you do MSBuild from console or only from Visual Studio?

**Comment by mnaoumov** [comment]
@Sam13 actually I had to rollback to the initial implementation where transformation happens before the build started. But I include **ResolveReferences** target to build all referenced projects. You mentioned that it is not working in your case and dependent assembly is missing. That's strange. Are you sure your template project has a project reference to the dependency project? Maybe you said a dependency on a solution level? Or maybe you put binary dependency? In those cases **ResolveRefernces** might not work

**Comment by Sam13** [comment]
@mnaoumov 
Thanks, with your latest fix it works!
Yes I'm sure I have a project reference to that. I'm building directly into VS.

**Comment by mnaoumov** [comment]
@Sam13 cool, thanks for your beta testing

**Comment by olograph** [comment]
Hi, I have a very blur and not so easy to debug (in a lifetime) error:

C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1249,5): error MSB3073: The command ""C:\Program Files (x86)\Common Files\microsoft shared\TextTemplating\10.0\TextTransform.exe" %1" exited with code 1.

The help menu of TextTransform.exe is outputed in VS build log.

Any idea how to solve this?

**Comment by mnaoumov** [comment]
@olograph, is it happening for any t4 templates? Or you have a special one?

In first case, please try to use [Process Monitor](https://technet.microsoft.com/en-us/sysinternals/processmonitor.aspx?f=255&MSPPError=-2147217396) to capture and see what is the exact command line is being executed and run it manually to see what's wrong there.

In second case, we might need to look at your template closer

**Comment by olograph** [comment]
Yes, it happens for every t4 template. They can be run manually though. I didn't know Process Monitor allowed that. It'll be faster than creating a VS solution and configure all symbols to debug the thing. MSBuild is fancy pantsy in debugging-wise.
I'll let you know about my results. Thanks

**Comment by olograph** [comment]
Nevermind my fast-responding friend! I created the problem. I won't explain cause I'm ashamed, but I learnt more about what Process Monitor can do. Have a great day!

**Comment by mnaoumov** [comment]
@olograph , great, glad to help

**Pull request merged**
