### PR TITLE
Include vs2019 paths for TextTransform

### PR DESCRIPTION
**Pull request by ernestns**

### CODE REVIEW

**Comment by stephenpatten** [comment]
This would be helpful for those of us who are using corporate window images that ONLY contain VS 2019 now.

Thank you,
Stephen

**Comment by barjonas** [comment]
Why not use the DevEnvDir environment variable at the top of the path list? That would make it forwards _and_ backwards compatible in many cases. I'm currently working around this issue with this in my .csproj.

```
  <PropertyGroup>
    <TextTransformPath>$(DevEnvDir)TextTransform.exe</TextTransformPath>
  </PropertyGroup>
```

**Comment by StormPooper** [comment]
The .csproj method works for VS directly, but when I try and call MSBuild on a specific project file, it still can't find it, so having this PR merged in would still be useful.

**Comment by jimmyheaddon** [comment]
Any update on this being merged in? :)

**Comment by jimmyheaddon** [comment]
For consistency sake, should the VS 2019 paths be at the top, given that the other paths appear to be in reverse chronological order, looking at the tooling version numbers?

**Comment by rperezretana** [comment]
Is this going to be approved? I been waiting for the fix for a while, and I am about to stop using this project just for this bug.

**Comment by Maximetinu** [comment]
Same problem here

**Comment by kzu** [comment]
Sorry it took so long, I'm back :)

**Pull request merged**
